services:

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: vitorneves/nginx:prod
    container_name: nginx
    ports:
      - 8080:80
    networks:
      - node-network
    depends_on:
      - app

  app: 
    container_name: app
    build: 
      context: ./
    networks:
      - node-network
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules 
    tty: true
    entrypoint: dockerize -wait tcp://db:3306 docker-entrypoint.sh node src/index.js
    command: node ./src/index.js
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db-nginx
    restart: always
    tty: true
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=dbroot
      - MYSQL_USER=node
      - MYSQL_PASSWORD=db
    networks:
      - node-network

networks:
  node-network:
